### PR TITLE
Add robot user

### PR DESCRIPTION
**Pull request by wazowsk1**
#230 

I have added a robot user to run the process inside the container.
I had to make /var/log writable for the robot user due to the /var/log/chromedriver log file.

### CODE REVIEW

**Comment by UltimateDogg** [comment]
all of the tests are failing with some variation of cant read /opt/robotframework/reports

`$ docker run --shm-size=1g -v `pwd`/test:/opt/robotframework/tests:Z -e BROWSER=chrome -e SCREEN_WIDTH=800 -e SCREEN_HEIGHT=600 docker-robot-framework:ci

[ ERROR ] Opening output file '/opt/robotframework/reports/output.xml' failed: Permission denied`

**Comment by wazowsk1** [comment]
I think the problem is the /test mount in Travis.

I think this folder has root permissions, though I am not sure how this exactly works in Travis.

**Comment by wazowsk1** [comment]
I was looking wrong, somehow /reports is given permission denied and not /test, so it has nothing to do with the mounting of a directory

I have tested it locally as the ci server does, but I do not get the same error

```
Tests.Faker                                                           | PASS |
7 critical tests, 7 passed, 0 failed
7 tests total, 7 passed, 0 failed
==============================================================================
Tests                                                                 | PASS |
7 critical tests, 7 passed, 0 failed
7 tests total, 7 passed, 0 failed
==============================================================================
Output:  /opt/robotframework/reports/output.xml
Log:     /opt/robotframework/reports/log.html
Report:  /opt/robotframework/reports/report.html
```

@UltimateDogg  do you have any idea why it fails on Travis?

**Comment by UltimateDogg** [comment]
try something like this in the travis ci script: https://stackoverflow.com/a/45244373

**Comment by wazowsk1** [comment]
> try something like this in the travis ci script: https://stackoverflow.com/a/45244373

this was not the issue, mounting the /test was fine. But I found the problem.

The volume was defined first and didn't allow me to chown it to the robot user, I moved the volume after the main RUN command

**Pull request merged**
