### PR TITLE
Issue #312 - Support datadriver + datadriver xls

### PR DESCRIPTION
**Pull request by UltimateDogg**
Support datadriver

### CODE REVIEW

**Review by ppodgorsek — DISMISSED** [review]

**Comment by ppodgorsek** [comment]
Thank you @UltimateDogg ! :) I approved the PR but will merge it after your other continuous integration PR is merged.

**Comment by UltimateDogg** [comment]
Pandas and numpy are apparently very beefy and have more than doubled build time (and counting)

**Comment by UltimateDogg** [comment]
9 mins to 39 minutes is quite the regression in build time

**Comment by ppodgorsek** [comment]
> 9 mins to 39 minutes is quite the regression in build time

Indeed! Do you know what is the difference in image size too? Are many more transitive dependencies installed?

**Comment by UltimateDogg** [comment]
I analyzed master (old), this branch (new) and this branch with the xls extra removed (new-no-xls) in dive. Old is 724 MB, New No XLS is 733 MB and New is 823 MB
old
new
new-no-xls

**Comment by ppodgorsek** [comment]
Thank you for your analysis. 100 MB to add XLS support feels like a big increase (11%) that a lot of users wouldn't need anyway.
I'd suggest we merge the datadriver change without XLS and keep a ticket/pull request open for XLS support. What do you think?
This would allow people to vote on that feature if it is really critical. (I'd like to keep the image as small as possible with as many features as possible)

**Comment by UltimateDogg** [comment]
Seems fair, i updated the pull to not have xls.

**Review by ppodgorsek — APPROVED** [review]

**Pull request merged**
